# Generated by Django 5.1.1 on 2024-09-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('groups', models.ManyToManyField(to='auth.group')),
                ('permissions', models.ManyToManyField(to='auth.permission')),
            ],
            options={
                'permissions': [('advanced', 'Advanced Permission'), ('pro', 'Pro Permission'), ('basic', 'Basic Permission')],
            },
        ),
    ]
