# Generated by Django 5.1.1 on 2024-09-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_subscription_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
