# Generated by Django 5.1.1 on 2024-09-24 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0012_alter_subscription_stripe_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionprice',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionprice',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscription'),
        ),
    ]
